### ISSUE TITLE
Selecting a filter doesn't work the first time, you have to select a second topic before filtering begins.

### ISSUE THREAD

**Issue by shawngrimes** [jonathanprozzi/learning-library-mvp-v1#1]
I recorded a screencast of the issue:
https://recordit.co/q7r0Tu0oO6

**Comment by jonathanprozzi** [comment]
Thanks Shawn (and thanks for the screencast!)

This issue is fixed by [this commit](https://github.com/jonathanprozzi/learning-library-mvp-v1/commit/46ab8d538fae84ef68cea13fec22fa74da6d9a8c).

Had an old state boolean that was toggling before the filter worked :)
